# Generated by Django 5.1.6 on 2025-03-01 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='runtime',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='filme',
            name='year',
            field=models.IntegerField(),
        ),
    ]
