# Generated by Django 5.1.6 on 2025-03-01 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmes', '0002_alter_filme_runtime_alter_filme_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filme',
            old_name='runtime',
            new_name='ano',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='year',
            new_name='duracao',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='genre',
            new_name='genero',
        ),
        migrations.RenameField(
            model_name='filme',
            old_name='language',
            new_name='linguagem',
        ),
        migrations.RemoveField(
            model_name='filme',
            name='title',
        ),
        migrations.AddField(
            model_name='filme',
            name='titulo',
            field=models.CharField(default=0, max_length=60),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('data_nascimento', models.DateField(max_length=50)),
                ('filmes', models.ManyToManyField(to='app_filmes.filme')),
            ],
        ),
    ]
