# Generated by Django 5.1.6 on 2025-03-02 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmes', '0005_alter_filme_id_alter_usuario_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='duracao',
            field=models.CharField(max_length=50),
        ),
    ]
