# Generated by Django 5.1.6 on 2025-03-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_filmes', '0006_alter_filme_duracao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='id',
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=150, primary_key=True, serialize=False, unique=True),
        ),
    ]
